stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/Machine_downtime.csv
    outs:
      - data/processed/train.csv

  detect_drift:
    cmd: python src/detect_drift.py
    deps:
      - src/detect_drift.py
      - data/processed/train.csv
      - data/live/batch_1.csv
      - data/live/batch_2.csv
      - data/live/batch_3.csv
    outs:
      - reports/drift_history.json
      - reports/drift_log.json

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
    outs:
      - models/model.pkl
      - reports/metrics.json

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - data/processed/train.csv
      - models/model.pkl
      - src/evaluate.py
    outs:
      - reports/eval_metrics.json
